# fly.toml app configuration file generated for advantcrest-server
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'advantcrest-server'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256MiB'
  cpu_kind = 'shared'
  cpus = 1
